### PR TITLE
add check for E221,E222,E227,E228 to the linter and extend it to dev/

### PR DESCRIPTION
**Pull request by fchapoton**
this is 

- extending the linter checks to the dev/ folder
- adding checks for E221, E222, E227 and E228 (all about spaces around operators)

### CODE REVIEW

**Comment by NathanDunfield** [comment]
Looks like these errors are from building the the binary extension [FXrays](https://github.com/3-manifolds/FXrays) for Python 3.12, not your changes.  But we should get everything working with Python 3.12 first to be sure, see [#112](https://github.com/3-manifolds/SnapPy/issues/112).

**Comment by culler** [comment]
I think I have fixed FXRays.  With Cython 3.0 the except clause apparently
needs to be included when declaring a function pointer.

- Marc

**Comment by fchapoton** [comment]
so it this now ready to merge ?

**Comment by NathanDunfield** [comment]
> so it this now ready to merge ?

Probably.  I think we've updated all the dependencies of `spherogram` to support Python 3.12, so try running the CI again.  If t's all green, I'll merge.

**Pull request merged**
